spring.datasource.url=jdbc:postgresql://localhost:5432/salgaki_test
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

whatsapp.api-base-url=https://graph.facebook.com/v25.0
whatsapp.phone-number-id=1171036512761779
whatsapp.business-account-id=1020630720656918
whatsapp.access-token = EAAVVUJZAaJFYBRsgXYSp4LvSEZCZA66QFbvLrKKBy0KTzrXLi4lgXHRtwuURz55ZCZAgCUZAgfSZA2VSQjWhYeEOf7rH3SK1UrZAZB3w15tBgNSGfCYN7dN8a3fuujtMYflEidcDZA5yA551YV4phOk8EZAsgOvkO1JZAPkXtpduetD7nxEyF4WMSrZAx6ALrBhQ6X40vQbwpTCY4MVZBAzLjQsHBl0fFF84wLsmcTvTaVGTzymHHhfUDhKkyofelOi7MjJZChUM5lsHGl8cvluqvxCwAgFugZDZD
whatsapp.document-filename=cardapio.pdf

# Logging para facilitar debug
logging.level.org.springframework.web=DEBUG
logging.level.com.salgaki=DEBUG